plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version "${forge_gradle_version}"
    id 'org.spongepowered.mixin' version "${mixin_gradle_version}"
    id 'wtf.gofancy.fancygradle' version "${fancy_gradle_version}"
}

configurations {
    embed
    implementation.extendsFrom(embed)
}

version = mod_version
group = mod_id
base.archivesName = mod_name

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: mappings_channel, version: mappings_version

    runs {
        client {
            args "--username=InDev"

            jvmArg "-Dmixin.env.disableRefMap=true"
            jvmArg "-Dmixin.hotSwap=true"
            jvmArg "-Dmixin.checks.interfaces=true"
            jvmArg "-Dmixin.debug.export=true"

            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }

        server {

            jvmArg "-Dmixin.hotSwap=true"
            jvmArg "-Dmixin.checks.interfaces=true"
            jvmArg "-Dmixin.debug.export=true"

            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }
    }
}

repositories {
    flatDir { dirs 'libs' }
    maven { url = 'https://www.cursemaven.com' }
    maven { url = 'https://maven.cleanroommc.com' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    embed "javax.validation:validation-api:${javax_validation_api_version}"
    embed "org.hibernate.validator:hibernate-validator:${hibernate_validator_version}"
    embed "org.glassfish:javax.el:${glassfish_el_version}"

    compileOnly "org.projectlombok:lombok:${lombok_version}"
    annotationProcessor "org.projectlombok:lombok:${lombok_version}"

    implementation("zone.rong:mixinbooter:${mixinbooter_version}") {transitive = false}
    annotationProcessor "zone.rong:mixinbooter:${mixinbooter_version}"

    implementation fg.deobf("curse.maven:jei-${jei_version}")
}

fancyGradle {
    patches {
        resources
        coremods
        asm
        mergetool
    }
}

mixin {
    add sourceSets.main, "mixins.brilliant_items.refmap.json"
    config "mixins.brilliant_items.vanilla.json"
}

processResources {
    var replaceProperties = [
            'mod_id'         : mod_id,
            'mod_name'       : mod_name,
            'version'        : mod_version,
            'mcversion'      : minecraft_version,
            'mod_description': mod_description,
            'mod_author'     : mod_author
    ]

    inputs.properties replaceProperties

    filesMatching('mcmod.info') {
        expand replaceProperties
    }
}

jar {
    finalizedBy 'reobfJar'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from {
        configurations.embed.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        // Exclude security signatures from third-party jars that break fat-jars
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.RSA'
        exclude 'META-INF/*.INF'
        exclude '**/module-info.class'
    }

    manifest {
        def attr = [:]
        attr['Specification-Title'] = mod_name
        attr['Specification-Vendor'] = mod_author
        attr['Specification-Version'] = '1'
        attr['Implementation-Title'] = mod_name
        attr['Implementation-Vendor'] = mod_author
        attr['Implementation-Version'] = mod_version
        attr['Implementation-Timestamp'] = new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        attr["MixinConfigs"] = "mixins.brilliant_items.vanilla.json"

        def currentTasks = gradle.startParameter.taskNames
        if (currentTasks[0] == 'build' || currentTasks[0] == 'assemble')
            attr['ForceLoadAsMod'] = "true"
        attributes(attr)
    }
}

sourceSets {
    main {
        output.resourcesDir = output.classesDirs.files.iterator().next()
    }
}